In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.models import Sequential

# Define the 5x5 input matrix
input_matrix = np.array([[1, 2, 3, 4, 5],
                         [6, 7, 8, 9, 10],
                         [11, 12, 13, 14, 15],
                         [16, 17, 18, 19, 20],
                         [21, 22, 23, 24, 25]], dtype=np.float32)

# Reshape input to match Conv2D input format (batch_size, height, width, channels)
input_matrix = input_matrix.reshape((1, 5, 5, 1))

# Define the 3x3 kernel
kernel = np.array([[1, 0, -1],
                   [1, 0, -1],
                   [1, 0, -1]], dtype=np.float32)

# Reshape kernel to match Conv2D kernel format (height, width, input_channels, output_channels)
kernel = kernel.reshape((3, 3, 1, 1))

# Function to perform convolution with different parameters
def apply_convolution(input_data, kernel, stride, padding):
    model = Sequential([
        Conv2D(filters=1, kernel_size=(3, 3), strides=(stride, stride), padding=padding,
               kernel_initializer=tf.keras.initializers.Constant(kernel), use_bias=False)
    ])
    return model.predict(input_data)

# Perform convolutions
outputs = {
    "Stride = 1, Padding = 'VALID'": apply_convolution(input_matrix, kernel, stride=1, padding='valid'),
    "Stride = 1, Padding = 'SAME'": apply_convolution(input_matrix, kernel, stride=1, padding='same'),
    "Stride = 2, Padding = 'VALID'": apply_convolution(input_matrix, kernel, stride=2, padding='valid'),
    "Stride = 2, Padding = 'SAME'": apply_convolution(input_matrix, kernel, stride=2, padding='same')
}

# Print the output feature maps
for key, value in outputs.items():
    print(f"{key} Output:\n", value.squeeze(), "\n")


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 216ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step
Stride = 1, Padding = 'VALID' Output:
 [[-6. -6. -6.]
 [-6. -6. -6.]
 [-6. -6. -6.]] 

Stride = 1, Padding = 'SAME' Output:
 [[ -9.  -4.  -4.  -4.  13.]
 [-21.  -6.  -6.  -6.  27.]
 [-36.  -6.  -6.  -6.  42.]
 [-51.  -6.  -6.  -6.  57.]
 [-39.  -4.  -4.  -4.  43.]] 

Stride = 2, Padding = 'VALID' Output:
 [[-6. -6.]
 [-6. -6.]] 

Stride = 2, Padding = 'SAME' Output:
 [[ -9.  -4.  13.]
 [-36.  -6.  42.]
 [-39.  -4.  43.]] 

